apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: drupal-mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        envFrom:
          - secretRef:
              name: drupal-mysql-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          subPath: dbdata
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: drupal-mysql-pvc