apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    app: drupal-pv
spec: 
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: "5Gi"
  hostPath:
    path: "/drupal-data"