apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "drupal-mysql-data"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi